name: Build PaNasMs
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: PaNasMs/panasms/.github/workflows/build.yml@4676200305d947b8f65f4906c7001cc9f6ddda32
    with:
      build_ref: 4676200305d947b8f65f4906c7001cc9f6ddda32
      backend_ref: ${{ github.sha }}
